// src/app/pattern-text.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-pattern-text',
  standalone: true,
  template: `
    <span
      [attr.data-shadow]="text"
      class="relative inline-block font-bold [text-shadow:0.02em_0.02em_0_var(--color-white)] after:absolute after:top-2 after:left-2 after:-z-10 after:content-[attr(data-shadow)] after:bg-[length:0.05em_0.05em] after:bg-clip-text after:text-transparent after:text-shadow-none after:bg-[linear-gradient(45deg,transparent_45%,var(--color-emerald-600)_45%,var(--color-emerald-600)_55%,transparent_0)] after:animate-shadanim {{ className }}"
    >
      {{ text }}
    </span>
  `
})
export class PatternTextComponent {
  @Input() text = '';
  @Input() className = '';
}

// src/components/ui/pattern-text.tsx
import React from 'react';
import { cn } from '@/lib/utils';

export function PatternText({
  text = 'Text',
  className,
  ...props
}: Omit<React.ComponentProps<'p'>, 'children'> & { text: string }) {
  return (
    <p
      data-shadow={text}
      className={cn(
        'relative inline-block text-[10em] font-bold',
        '[text-shadow:0.02em_0.02em_0_var(--color-background)]',
        'after:absolute after:top-2 after:left-2 after:-z-1 after:content-[attr(data-shadow)]',
        'after:bg-size-[0.05em_0.05em] after:bg-clip-text after:text-transparent after:text-shadow-none',
        'after:bg-[linear-gradient(45deg,transparent_45%,var(--color-foreground)_45%,var(--color-foreground)_55%,transparent_0)]',
        'after:animate-[shadanim_15s_linear_infinite]',
        className,
      )}
      {...props}
    >
      {text}
    </p>
  );
}
